apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    app: hello-world-pod
spec:
  containers:
  - env:
    - name: MESSAGE
      value: Hi! I'm an environment variable
    image: myartifacthome.jfrog.io/default-docker-virtual/practicalopenshift/hello-world
    imagePullPolicy: Always
    name: hello-world-override
    resources: {}
  imagePullSecrets:
    - name: regcred
